name = "joybuy-price-history"
main = "src/index.js"
compatibility_date = "2026-08-25"

[[d1_databases]]
binding = "DB"
database_name = "joybuy_price_history"
database_id = "24718ee9-f606-47cd-a4d8-4c2899c684ad"

[triggers]
crons = ["0 3 * * *"]

[vars]
TRACKED_PRODUCTS_JSON = """
[
  {
    "url": "https://www.joybuy.de/dp/%E9%A6%99%E6%BA%90-%E5%AB%A9%E7%BE%8A%E5%8D%B7-300g/101322517?requestIdentity=flashSale"
  },
  {
    "url": "https://www.joybuy.de/dp/%E6%B4%81%E6%9F%94-face-%E7%B2%89%E8%89%B2%E6%9F%94%E8%BD%AF%E6%8A%BD%E5%8F%96%E5%BC%8F%E9%9D%A2%E5%B7%BE%E7%BA%B83-%E5%B1%828-%E5%8C%85-x/10286300?requestIdentity=flashSale"
  },
  {
    "url": "https://www.joybuy.de/dp/%E9%BA%BB%E5%85%AD%E8%AE%B0-%E8%92%9C%E9%A6%99%E9%AD%94%E8%8A%8B%E8%B4%A1%E8%8F%9C-20%E8%A2%8B%E7%9B%92%E8%A3%85300g/100946343?requestIdentity=flashSale"
  },
  {
    "url": "https://www.joybuy.de/dp/senhoglb-1-%E6%A0%BC%E6%A8%AA%E5%90%91-a4-%E9%87%91%E5%B1%9E%E7%BD%91%E6%A0%BC%E5%A3%81%E6%8C%82%E6%96%87%E4%BB%B6%E6%9E%B6%E9%93%B6%E8%89%B2%E6%96%B0%E5%B9%B4%E4%BF%83%E9%94%80%E7%A4%BC%E5%93%81%E4%BC%98%E9%80%89/10372137?requestIdentity=searchCategory"
  },
  {
    "url": "https://www.joybuy.de/dp/cocacola-original-dose-vorratspack-18x033l/100736603?requestIdentity=bestsellerRankList"
  },
  {
    "url": "https://www.joybuy.de/dp/102744800?requestIdentity=storePick"
  },
  {
    "url": "https://www.joybuy.de/dp/10468517?requestIdentity=flashSale&ref_sku=10286300"
  },
  {
    "url": "https://www.joybuy.de/dp/10328909"
  },
  {
    "url": "https://www.joybuy.de/dp/10382745?ref_sku=10382745&requestIdentity=recommendProductDetailPage"
  },
  {
    "url": "https://www.joybuy.de/dp/102395532?ref_sku=102395532&requestIdentity=searchShop"
  }
]
"""
